# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "981838db3a8cdcc6d83263dcec01e8e3"
name = "banner"
handle = "banner-344"
application_url = "https://increasing-beans-niger-mic.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://increasing-beans-niger-mic.trycloudflare.com/auth/callback",
  "https://increasing-beans-niger-mic.trycloudflare.com/auth/shopify/callback",
  "https://increasing-beans-niger-mic.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
